"""remove asdf column on simple_people

Revision ID: 0a92557cb7ad
Revises: aa1003e490d3
Create Date: 2024-12-13 18:25:51.358976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a92557cb7ad'
down_revision = 'aa1003e490d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.drop_column('asdf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asdf', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
