"""rename renamed back to bio on simple_people

Revision ID: b4493a0959cd
Revises: ce6661eba2b7
Create Date: 2024-12-13 19:02:45.613968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4493a0959cd'
down_revision = 'ce6661eba2b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=2000), nullable=True))
        batch_op.drop_column('renamed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renamed', sa.VARCHAR(length=2000), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
