"""rename bio to renamed on simple_people

Revision ID: ce6661eba2b7
Revises: 0a92557cb7ad
Create Date: 2024-12-13 18:26:45.006177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6661eba2b7'
down_revision = '0a92557cb7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renamed', sa.String(length=2000), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=2000), nullable=True))
        batch_op.drop_column('renamed')

    # ### end Alembic commands ###
